/* ========================================================================
   TEXTOS FIXOS DOS PROMPTS — módulo separado do index.ts (v63).
   ========================================================================
   Este arquivo contém, SEM NENHUMA ALTERAÇÃO DE CONTEÚDO, três blocos que até
   a v62 viviam dentro do index.ts: a regra de notação química, as instruções
   por recurso visual (protocolo de imagem em 8 seções, versão geral e a de
   Biologia, gráfico, tabela) e o formato de entrega (JSON_SCHEMA_TXT). Foram
   movidos para cá apenas para que o index.ts fique menor de implantar; o
   index.ts os importa deste mesmo caminho no repositório (GitHub, branch
   main), exatamente como já faz com app_data.json — o empacotador do Deno
   embute o conteúdo na hora do deploy, e em produção não há chamada de rede.
   Consequência prática: ANTES de implantar uma nova versão da função, este
   arquivo precisa estar publicado no GitHub (push). */

/* Notação química — a fórmula chega ao estudante pronta, nunca como comando.
   O PDF, o Word e o HTML do aplicativo imprimem Unicode direto; LaTeX ou "H2O"
   chegariam ao papel exatamente assim, e a auditoria do app barra a exportação. */
export const NOTACAO_QUIMICA = `

═══════ NOTAÇÃO QUÍMICA — REGRA ABSOLUTA DE FORMATAÇÃO ═══════
Toda fórmula, íon, equação, isótopo ou unidade científica sai PRONTA, em caracteres
Unicode, diretamente legível. Vale para texto-base, comando, tabelas, alternativas,
gabarito, resolução comentada, comentário de cada alternativa e prompt de imagem.

PROIBIDO SEM EXCEÇÃO: LaTeX, KaTeX, MathJax, \\ce{}, \\frac, $...$, _{ }, ^{ },
tags HTML (<sub>, <sup>), entidades HTML, blocos de código, crases, barras
invertidas, chaves de formatação, delimitadores matemáticos, Markdown matemático.
A fórmula aparece como H₂SO₄ — nunca como um comando a ser renderizado depois.

ÍNDICES (quantidade de átomos) em algarismo INFERIOR ₀₁₂₃₄₅₆₇₈₉:
H₂O · CO₂ · NH₃ · CH₄ · H₂SO₄ · H₃PO₄ · Ca(OH)₂ · Al₂O₃ · Fe₂(SO₄)₃ · C₆H₁₂O₆ · C₁₂H₂₂O₁₁
NUNCA: H2O, H 2 O, H²O, Al2(SO4)3. O símbolo do elemento fica no nível da linha.

CARGAS no canto superior direito, NÚMERO ANTES DO SINAL, com ⁰¹²³⁴⁵⁶⁷⁸⁹⁺⁻:
Na⁺ · Ca²⁺ · Fe³⁺ · Al³⁺ · Cl⁻ · OH⁻ · NH₄⁺ · NO₃⁻ · SO₄²⁻ · CO₃²⁻ · PO₄³⁻ ·
MnO₄⁻ · Cr₂O₇²⁻ · [Fe(CN)₆]⁴⁻
NUNCA: Ca+2, Ca2+, SO4-2, SO₄-2, SO²⁻₄, ⁺².

COEFICIENTES são números comuns ANTES da fórmula: 2 H₂(g) + O₂(g) → 2 H₂O(l).
Coeficiente nunca vira índice; para balancear não se altera a fórmula (2 H₂O, nunca H₄O₂).

SETAS: → é UM ÚNICO CARACTERE (U+2192). É PROIBIDO montar seta com hífen, sinal de
maior, de menor ou de igual. Nunca escreva -> --> => ==> <- <-> <=> <==> como seta.
Nunca use imagem, emoji ou ícone no lugar do símbolo. Cada seta tem um significado:
→ reação da esquerda para a direita · ← sentido inverso · ⇌ EQUILÍBRIO QUÍMICO ·
↔ ressonância · ↑ desprendimento de gás · ↓ formação de precipitado.
↔ NÃO substitui ⇌. Reagentes antes da seta, produtos depois. Nunca sinal de
igualdade no lugar da seta. Ligação química (–, =, ≡) NÃO é seta de reação.
Estados físicos logo após a fórmula: (s) (l) (g) (aq).
Ex.: AgNO₃(aq) + NaCl(aq) → AgCl(s) + NaNO₃(aq).
Condição de reação (temperatura, pressão, luz, catalisador) vai em frase junto à
equação — não fragmente a seta para encaixá-la, e não trate catalisador como
reagente consumido.

BALANCEAMENTO: toda equação apresentada como completa está balanceada (salvo quando
a própria questão pedir que o estudante balanceie). Conte os átomos dos dois lados,
confira a conservação da massa E da carga, use os menores coeficientes inteiros.
Ex.: 4 Fe(s) + 3 O₂(g) → 2 Fe₂O₃(s).

ORGÂNICA: – ligação simples, = dupla, ≡ tripla. CH₃–CH₃ · CH₂=CH₂ · HC≡CH ·
CH₃–CH₂–OH · CH₃–COOH · CH₃–CO–CH₃. Não altere hidrogênios, grupos ou ligações.
Se a estrutura for complexa demais para representação linear segura, peça fórmula
estrutural em IMAGEM — não invente a estrutura.

ISÓTOPOS: número de massa acima e número atômico abaixo, antes do símbolo —
¹⁴₆C · ²³₁₁Na · ²³⁸₉₂U · ⁴₂He · e⁻ · p⁺ · n⁰ · β⁻. Não inverta os dois.

GRANDEZAS não viram índice nem expoente: 25 °C · 2 mol · 0,5 mol/L · 1,0 atm ·
250 mL · pH 7 · 6,02 × 10²³ · 1,5 × 10⁻³ mol/L. No expoente matemático o sinal vem
antes do número (10⁻³); na carga, depois (Ca²⁺).

CONSISTÊNCIA: a mesma substância mantém a MESMA grafia no texto-base, no comando,
nos dados, na tabela, nas alternativas, no gabarito e na resolução. Maiúscula e
minúscula são significado: Co (cobalto) ≠ CO (monóxido de carbono).

CASOS DE TESTE — a notação de saída tem de sair exatamente assim:
H₂SO₄ · Al₂(SO₄)₃ · SO₄²⁻ · NH₄⁺ · [Fe(CN)₆]⁴⁻ · CuSO₄·5H₂O
2 H₂(g) + O₂(g) → 2 H₂O(l)
N₂(g) + 3 H₂(g) ⇌ 2 NH₃(g)
Ag⁺(aq) + Cl⁻(aq) → AgCl(s)
Zn(s) → Zn²⁺(aq) + 2 e⁻

JSON: as fórmulas ficam como caracteres Unicode normais, em UTF-8, nunca como
código ou sequência de escape.

BLOQUEIO: se uma fórmula não puder ser confirmada com segurança, não invente. Deixe
no campo correspondente o aviso "REVISÃO QUÍMICA NECESSÁRIA: a fórmula ou equação
não pôde ser validada com segurança."`;

export const RECURSO_INSTRUCOES: Record<string, string> = {
  nenhum: `Recurso visual: NENHUM. Não inclua gráfico, tabela ou imagem. Explore a situação-problema apenas por meio do texto-suporte. Deixe o campo "visual" como null e "recurso" como "nenhum".`,
  imagem: `Recurso visual: IMAGEM. A questão deve depender de uma imagem/ilustração pedagogicamente necessária (nunca meramente decorativa) para ser respondida corretamente — por exemplo: esquema anatômico, diagrama de processo, mapa, representação de fenômeno, estrutura, infográfico. Preencha "recurso":"imagem" e "visual" com: {"tipo":"imagem","descricao":"<legenda em português explicando o que a imagem mostra e por que ela é necessária para resolver a questão>","promptImagem":"<especificação técnica em INGLÊS, redigida conforme o PROTOCOLO OBRIGATÓRIO abaixo>"}. ⚠️ TIPO DO CAMPO — leia com atenção: "promptImagem" e "descricao" são, cada um, UMA ÚNICA STRING de texto corrido. As 8 seções do protocolo ficam DENTRO dessa string, uma após a outra, cada uma iniciada pelo seu título numerado (ex.: "1. SCENE AND VIEWPOINT: ..."), separadas por quebra de linha. NUNCA entregue "promptImagem" como objeto JSON — nem uma chave por seção, nem {"tipo":..., "valor":...}, nem qualquer outro aninhamento. O gerador de imagens só recebe TEXTO: um objeto chega a ele vazio, e a imagem sai sobre um assunto aleatório, sem nenhuma relação com a questão.

⚠️ PROTOCOLO OBRIGATÓRIO DE ESPECIFICAÇÃO DA IMAGEM
O gerador NÃO conhece a questão, NÃO lê o texto-base, NÃO vê o comando e NÃO infere nada: desenha exatamente e só o que estiver no "promptImagem". Toda ambiguidade vira erro — seta invertida, rótulo no elemento errado, elemento ausente, número ilegível. Portanto o "promptImagem" NÃO é descrição literária nem frase única: é ESPECIFICAÇÃO TÉCNICA COMPLETA, em inglês, elemento por elemento, com posição e direção explícitas, nas 8 seções abaixo, nesta ordem, cada uma com seu título em inglês:

🎯 FIDELIDADE OBRIGATÓRIA AO ENUNCIADO — antes de escrever qualquer seção, releia integralmente o texto-base, o comando, as alternativas e a resolução e extraia TODOS os dados concretos ali contidos: cada objeto citado, cada valor numérico, cada posição relativa, cada direção de causa-efeito, cada processo ou fenômeno descrito, cada relação entre elementos (o que vem antes/depois, o que está à esquerda/direita, o que é maior/menor, o que aumenta/diminui, o que está ligado a quê). Nenhum desses dados pode ficar de fora do "promptImagem", e nenhum dado inventado que contradiga o enunciado pode entrar na imagem. Se o enunciado descreve, por exemplo, um circuito elétrico em série ou em paralelo, resistores, capacitores, uma reação química específica, um objeto em movimento com velocidade e sentido definidos, ou qualquer outro elemento técnico com propriedades exatas, a imagem tem de refletir EXATAMENTE essas propriedades, sem aproximação e sem ambiguidade. É PROIBIDO entregar uma especificação genérica que sirva para "qualquer questão parecida" — a especificação tem de servir apenas para ESTA questão, com estes dados exatos. Toda vez que restar dúvida sobre um detalhe (direção de uma seta, posição de um elemento, valor de uma grandeza), a resposta está na resolução da questão: releia-a antes de decidir.

1. SCENE AND VIEWPOINT — o que a figura é, em uma frase, e o ponto de vista exato: front view, side view, top-down view, cross-section, exploded view ou three-quarter view. Declare a orientação absoluta (ex.: "the plant is upright, roots at the bottom, leaves at the top") e o AMBIENTE: por padrão um ambiente real, coerente com a cena, com profundidade e atmosfera (ex.: "shallow tropical reef bathed in shafts of sunlight, softly blurred background"). Reserve deliberadamente uma área visualmente calma (céu, água, parede, fundo desfocado) do lado em que os rótulos vão entrar. Fundo liso ("plain white background") só em conteúdo puramente abstrato/matemático: gráfico de eixos ou figura geométrica pura. CIRCUITOS ELÉTRICOS, COMPONENTES E APARELHOS NUNCA são exceção: um circuito em série ou em paralelo, resistores, capacitores, pilhas, fios, multímetros e demais componentes físicos têm de ser especificados como OBJETOS REAIS fotografados/renderizados sobre uma bancada, protoboard ou placa de circuito — com fios reais coloridos, resistores reais com faixas de cores visíveis, terminais e soldas quando fizer sentido — jamais como diagrama esquemático abstrato com símbolos de livro didático (nada de linhas retas com símbolos de circuito, zigue-zague genérico para resistor ou par de traços para pilha). Peça, em inglês, termos como "photorealistic photograph of a real electronics workbench, real breadboard or PCB, real resistors with visible color bands, real copper wires, real battery pack" sempre que o assunto envolver circuitos ou componentes eletrônicos.

2. ELEMENT INVENTORY — lista numerada de TODOS os elementos, com quantidade explícita ("exactly three test tubes", "one arrow"). O gerador inventa elementos extras; contar reduz isso. Nada fora desta lista pode aparecer.

3. LAYOUT AND POSITION — para CADA elemento, a posição absoluta (left / center / right com top / middle / bottom) E em relação aos vizinhos, com o lado sempre explícito. Ex.: "the beaker sits at the center-bottom; the flame is directly beneath the beaker; the thermometer is inserted from above, tilted about 30 degrees to the right". PROIBIDO escrever só "next to", "near" ou "beside" sem dizer de que lado. Se o enunciado descrever explicitamente a posição de algum elemento (à esquerda, acima, no topo, entre dois pontos etc.), a posição na imagem tem de ser IDÊNTICA à descrita — nunca uma posição diferente, ainda que visualmente plausível.

4. ARROWS — a causa mais frequente de erro. Para CADA seta, uma linha própria contendo, nesta ordem: origem, destino, onde fica a ponta (arrowhead), direção na tela e o que representa. Modelo: "One arrow starting at the right edge of the sun and ending at the top surface of the leaf, with the arrowhead touching the leaf and pointing down-left, representing incident sunlight." TERMINANTEMENTE PROIBIDO "an arrow between A and B", "arrows connecting the parts", "arrows showing the cycle" ou qualquer forma sem origem, destino e ponta — sem isso o gerador escolhe o sentido e frequentemente o inverte. Se o SENTIDO for parte do que a questão avalia (fluxo de energia, corrente elétrica, movimento, sentido de reação, cadeia alimentar, ciclo biogeoquímico), repita a direção uma segunda vez, com outras palavras, ao final. O sentido de CADA seta tem de corresponder exatamente ao que o texto-base, o comando, as alternativas ou a resolução afirmam sobre aquele fenômeno — nunca um sentido genérico ou "provável"; havendo qualquer dúvida sobre o sentido correto, releia a resolução antes de decidir, pois é ali que o sentido correto sempre está implícito ou explícito.

5. TEXT LABELS — para CADA rótulo, escreva: o texto EXATO entre ASPAS SIMPLES, o elemento a que pertence, o lado em que fica e se há linha de chamada. Modelo: the label 'Cloroplasto' placed immediately to the right of the green organelle, connected to it by a thin straight leader line. Use aspas simples em TODA a especificação da imagem — ela viaja dentro de um campo JSON, e aspas duplas não escapadas quebram a resposta inteira. Regras: (a) TODO texto visível deve estar EM PORTUGUÊS, ainda que a especificação esteja em inglês — inclua "all visible text must be rendered exactly as written above, in Portuguese, with correct spelling"; (b) o rótulo fica FORA do contorno do elemento, nunca sobreposto; (c) nem rótulo sem elemento, nem elemento essencial sem rótulo; (d) se dois rótulos correrem risco de se aproximar, declare os lados opostos; (e) declare o tamanho ("labels in a clear sans-serif typeface, large enough to be read when the image is printed at half page width").

6. NUMBERS, SCALES AND MEASUREMENT MARKS — havendo dado referencial (régua ou escala graduada, marcações de altura, distância, tempo, velocidade, temperatura, valores em eixo, unidades), liste os valores EXATOS, onde cada um aparece e de que lado do traço fica impresso. Modelo: "a vertical graduated ruler along the left side, with clearly legible labeled tick marks at 5 m, 10 m, 15 m and 20 m, each number printed to the left of its own tick". Os valores devem ser exatamente os mesmos do texto-base, do comando, das alternativas e da resolução — nunca aproximados nem arredondados de outra forma.

7. STYLE AND LEGIBILITY — a imagem tem DUAS CAMADAS, e as duas são obrigatórias.

   ⛔ REGRA NÃO NEGOCIÁVEL DE REALISMO — vale para TODA imagem, sem exceção: ela tem de ser ULTRA-REALISTA ou, no mínimo, SEMI-ULTRA-REALISTA. É PROIBIDO entregar uma imagem simples, chapada, tipo clipart ou tipo desenho esquemático de livro didático genérico — mesmo quando o assunto pareceria "simples" à primeira vista (um objeto do dia a dia, uma célula, uma reação química), a imagem tem de receber o mesmo padrão de produção fotorrealista de uma cena complexa. Sempre que o conteúdo permitir (isto é, sempre que a seção 1 não exigir fundo liso por se tratar de conteúdo puramente abstrato/matemático — gráfico de eixos ou figura geométrica pura), PREFIRA renderização TRIDIMENSIONAL. Isto SEMPRE inclui circuitos elétricos e componentes eletrônicos, que devem ser tratados como objetos reais fotografados, nunca como esquema plano. Peça, em inglês, termos como "photorealistic 3D render, three-dimensional CGI model, physically-based rendering, volumetric lighting and shadow, realistic depth" combinados com o padrão cinematográfico da Camada 1 abaixo — a cena deve parecer modelada em três dimensões e fotografada, nunca desenhada em plano único.

   ▸ CAMADA 1 — BASE CINEMATOGRÁFICA (beleza e impacto), no padrão National Geographic, BBC Earth, Planet Earth e IMAX, preferencialmente com renderização 3D fotorrealista. Peça, em inglês: "ultra-realistic 4K/8K photography, three-dimensional photorealistic render when applicable, ultra definition, razor-sharp focus on the subject, cinematic composition, dramatic directional natural lighting, rich material textures and micro-detail, deep saturated color, atmospheric depth of field, epic sense of scale and grandeur, museum-quality documentary photography". Bonita, imponente e memorável — nunca chapada, genérica, simples, borrada ou pixelizada.

   ▸ CAMADA 2 — CAMADA DE ANOTAÇÃO (precisão). Por cima da cena, camada vetorial limpa com as setas (seção 4), os rótulos (seção 5) e as marcações (seção 6), em princípios de UI/UX: hierarquia visual clara, tipografia sans-serif de tamanhos consistentes, mesma cor para o mesmo tipo de elemento, espaçamento generoso, contraste garantido contra o que está atrás. Peça, em inglês: "clean vector annotation overlay in modern UI/UX infographic style, consistent labeling system, clear visual hierarchy, high contrast between annotation and background, thin leader lines, subtle translucent backing plates or soft halo behind text wherever the scene behind it is busy".

   ▸ REGRA DE PRECEDÊNCIA (não negociável): a Camada 1 NUNCA prejudica a Camada 2. Se a cena ameaçar a leitura de um número, rótulo ou seta, a cena cede — menos detalhe, área escurecida/desfocada atrás da anotação, ou mais espaço. Declare no prompt, em inglês: "the cinematic scene must never obscure the annotation layer; every label, arrow and numeric mark must remain fully legible". Uma imagem deslumbrante com a régua ilegível é uma imagem inútil para a questão.

   ▸ FIDELIDADE: o esplendor jamais custa exatidão. A cena reflete EXATAMENTE a situação-problema — mesmo objeto, mesmo processo, mesmo momento, mesmos valores. PROIBIDO acrescentar elementos espetaculares alheios à questão (relâmpagos, erupções, fauna extra, luz impossível) só para impressionar: tudo que a questão não previu vira ruído ou erro conceitual.

8. NEGATIVE CONSTRAINTS — encerre listando o que NÃO pode aparecer: "no decorative text, no watermark, no signature, no caption bar, no extra arrows, no additional objects beyond those listed above, no duplicated labels, no cropped or cut-off elements, no text in any language other than Portuguese, no flat clipart or generic cartoon style, no simple or plain illustration, no basic flat 2D line art when a realistic or three-dimensional rendering is possible, no blurry, pixelated or low-detail rendering, no annotation hidden or obscured by the scene".

VERIFICAÇÃO ANTES DE ENTREGAR: releia a "descricao", o texto-base, o comando, as alternativas e a resolução e confirme que (i) todo elemento citado como visível consta do ELEMENT INVENTORY; (ii) toda seta tem origem, destino, ponta e direção na seção ARROWS; (iii) todo rótulo tem texto exato, elemento dono e lado; (iv) todo número citado na questão aparece com o MESMO valor na seção NUMBERS; (v) nada foi afirmado na "descricao" que não esteja especificado; (vi) todo dado numérico, toda posição relativa e todo sentido de seta especificados correspondem exatamente ao texto-base, ao comando, às alternativas e à resolução — nenhum deles é genérico ou aproximado; (vii) se a questão envolve circuito elétrico, componente eletrônico ou aparelho técnico, ele foi especificado como objeto real fotografado/renderizado, nunca como esquema abstrato. Nunca descreva na "descricao" um dado que não esteja visível na imagem, nem deixe na imagem um dado essencial que a "descricao" não mencione.`,

  imagem_biologia: `Recurso visual: IMAGEM (BIOLOGIA). A questão deve depender de uma imagem/ilustração pedagogicamente necessária (nunca meramente decorativa) para ser respondida corretamente — esquema anatômico, diagrama de processo, corte, ciclo biológico, cladograma, cadeia/teia alimentar, comparação entre condições, mapa ou infográfico. Preencha "recurso":"imagem" e "visual" com: {"tipo":"imagem","descricao":"<legenda em português explicando o que a imagem mostra e por que ela é necessária para resolver a questão>","promptImagem":"<especificação técnica em INGLÊS, redigida conforme o PROTOCOLO OBRIGATÓRIO — BIOLOGIA abaixo>"}. ⚠️ TIPO DO CAMPO — leia com atenção: "promptImagem" e "descricao" são, cada um, UMA ÚNICA STRING de texto corrido. As 8 seções do protocolo ficam DENTRO dessa string, uma após a outra, cada uma iniciada pelo seu título numerado (ex.: "1. SCENE AND VIEWPOINT: ..."), separadas por quebra de linha. NUNCA entregue "promptImagem" como objeto JSON — nem uma chave por seção, nem {"tipo":..., "valor":...}, nem qualquer outro aninhamento. O gerador de imagens só recebe TEXTO: um objeto chega a ele vazio, e a imagem sai sobre um assunto aleatório, sem nenhuma relação com a questão.

🧬 FUNÇÃO PEDAGÓGICA DA IMAGEM (raciocínio interno seu — nunca copie o conteúdo desta seção para dentro do "promptImagem" nem da "descricao"): antes de especificar qualquer elemento, decida com clareza (a) qual conteúdo de Biologia a imagem representa; (b) qual fenômeno, estrutura ou relação o aluno precisa analisar; (c) quais informações têm de estar visíveis para permitir essa análise; (d) quais informações o aluno deve inferir a partir do que estiver visível, sem que estejam escritas na imagem; (e) quais informações NÃO podem aparecer, porque entregariam a resposta; (f) se a imagem é indispensável à resolução ou apenas contextual; (g) qual simplificação didática é cientificamente aceitável sem distorcer o conteúdo. O gabarito e a resolução comentada servem para orientar essas decisões, mas nenhuma palavra deles pode aparecer, literal ou disfarçada, no "promptImagem" nem na "descricao" de um jeito que revele a resposta.

⚠️ PROTOCOLO OBRIGATÓRIO DE ESPECIFICAÇÃO DA IMAGEM — BIOLOGIA
O gerador NÃO conhece a questão, NÃO lê o texto-base, NÃO vê o comando e NÃO infere nada: desenha exatamente e só o que estiver no "promptImagem". Toda ambiguidade vira erro científico — seta invertida, estrutura confundida com outra homóloga/análoga, compartimento anatômico errado, rótulo no elemento errado, contagem errada de organelas/cromossomos/organismos, número ilegível. Portanto o "promptImagem" NÃO é descrição literária nem frase única: é ESPECIFICAÇÃO TÉCNICA COMPLETA, em inglês, elemento por elemento, com posição, orientação anatômica e direção explícitas, nas 8 seções abaixo, nesta ordem, cada uma com seu título em inglês.

🎯 FIDELIDADE OBRIGATÓRIA AO ENUNCIADO — antes de escrever qualquer seção, releia integralmente o texto-base, o comando, as alternativas e a resolução e extraia TODOS os dados concretos ali contidos: cada estrutura citada, cada organismo, cada valor numérico ou quantidade, cada posição relativa, cada direção de fluxo/processo, cada fenômeno biológico descrito, cada relação entre elementos (o que está dentro/fora, adjacente, comunicante, à esquerda/direita do organismo — não da imagem). Nenhum desses dados pode ficar de fora do "promptImagem", e nenhum dado inventado que contradiga o enunciado ou a literatura científica pode entrar na imagem. Sempre que restar dúvida sobre um detalhe (sentido de uma seta, posição de uma estrutura, quantidade de um elemento), a resposta está na resolução comentada: releia-a antes de decidir.

1. SCENE AND VIEWPOINT — declare, em uma frase, o tipo exato de representação: esquema científico bidimensional, ilustração anatômica, corte transversal ou longitudinal, vista externa ou interna, representação microscópica esquemática, sequência de acontecimentos, ciclo biológico, cladograma/árvore filogenética, cadeia ou teia alimentar, comparação entre condições, ou composição de múltiplos painéis. NÃO peça aparência de fotografia real nem de micrografia real quando o conteúdo for uma construção esquemática (célula, corte de órgão, ciclo, cladograma) — nesse caso declare explicitamente "photorealistic 3D scientific illustration/render of a schematic diagram" (nunca "flat clipart", nunca "cartoon"), preservando ao mesmo tempo a precisão anatômica: use tridimensionalidade só quando ajudar a compreender relações espaciais reais, sem efeitos cinematográficos, iluminação dramática ou texturas que possam alterar a interpretação das estruturas. Cladogramas, árvores filogenéticas e cadeias/teias alimentares são diagramas relacionais abstratos (nós e ramificações/setas) — para esses, use fundo liso ("plain white or neutral background"), no mesmo padrão de exceção já previsto para gráficos e figuras geométricas puras. Para os demais tipos (esquema anatômico, corte, ciclo, comparação), declare a orientação absoluta (ex.: "the plant is upright, roots at the bottom, leaves at the top"), o AMBIENTE (real e coerente com a cena, ex.: "shallow tropical reef" — ou neutro, quando a clareza científica exigir) e reserve deliberadamente uma área visualmente calma do lado em que os rótulos vão entrar. Declare também o FORMATO: proporção da imagem conforme o conteúdo, orientação horizontal ou vertical, margens livres para impedir cortes de elementos, quantidade de painéis e organização em linhas/colunas quando houver comparação ou sequência, área reservada ao desenho principal e áreas reservadas a títulos/rótulos/legendas. Quando houver muitos elementos ou múltiplos painéis, use coordenadas relativas de 0% a 100% (origem no canto superior esquerdo, eixo horizontal crescendo para a direita, eixo vertical crescendo para baixo) para fixar a posição de cada painel/estrutura principal — a conexão correta entre estruturas tem prioridade sobre o cumprimento rígido de uma coordenada. Se a figura representar uma sequência, ciclo ou relação entre organismos (inclusive ciclos parasitários), declare aqui a lista ordenada de etapas, indicando para cada uma: organismo/estrutura presente, estágio de desenvolvimento, ambiente/compartimento e evento representado — em ciclos parasitários, diferencie explicitamente hospedeiros, vetores, ambiente externo, estágios infectantes e diagnósticos, vias de entrada/saída e locais de desenvolvimento, quando pertinente à questão.

2. ELEMENT INVENTORY — lista numerada de TODOS os elementos, cada um com: nome/identificador interno (nunca impresso na imagem, a menos que solicitado), quantidade EXATA ("exactly four mitochondria", "one arrow"), localização, forma, tamanho relativo, orientação, cor e preenchimento, contorno, estruturas internas visíveis, relação com os demais elementos, e quais elementos análogos NÃO podem aparecer. Não escreva "incluir organelas" — liste exatamente quais organelas aparecem e quais características permitem reconhecê-las. Não escreva "vários organismos" quando a quantidade tiver significado biológico na questão — informe o número exato. Diferencie estruturas que exigem contagem rigorosa (cromossomos, cromátides, organelas, organismos de uma população) das que são meramente ilustrativas. Nada fora desta lista pode aparecer.

3. LAYOUT AND POSITION — para CADA elemento, a posição absoluta (left/center/right com top/middle/bottom) e em relação aos vizinhos, com o lado sempre explícito — PROIBIDO "next to", "near" ou "beside" sem dizer de que lado. Em representações anatômicas, celulares ou histológicas, especifique também: o organismo/órgão/tecido/tipo celular retratado; a vista adotada (frontal, dorsal, ventral, lateral, ou outra); o tipo e plano de corte; a orientação dos eixos anatômicos; quais estruturas ficam no interior de outras; quais são adjacentes; quais compartimentos se comunicam e quais barreiras os separam; quais estruturas estão à frente/atrás; e quais partes foram removidas ou tornadas transparentes para permitir a visualização (declare que é um recurso didático). Diferencie SEMPRE a direita/esquerda do organismo da direita/esquerda da imagem — nunca escreva só "lado direito" quando houver risco de confusão. Havendo janela de ampliação, marque claramente sua origem — ela não pode parecer uma estrutura adicional do organismo. Se a questão comparar duas ou mais condições (ex.: estômato aberto/fechado, célula normal/alterada, dois estágios de um processo), use o mesmo enquadramento, o mesmo estilo de desenho, a mesma escala (salvo indicação contrária), posicione estruturas equivalentes em locais correspondentes, use as mesmas cores para elementos equivalentes e modifique APENAS a característica relacionada à comparação — proibido introduzir diferenças decorativas que funcionem como pista involuntária da resposta.

4. ARROWS — a causa mais frequente de erro. Trate CADA seta como uma ficha própria, com todos os campos a seguir declarados por extenso (os códigos S1, S2 etc. são só para sua organização e NUNCA aparecem impressos na imagem): função (identificação, deslocamento, fluxo, transformação, transferência de energia); origem (elemento e ponto exato de onde parte); destino (elemento e ponto exato onde termina); ponta (localização e orientação exatas); trajeto (reto, curvo, em arco ou segmentado); passagem (regiões pelas quais deve passar); restrições (estruturas que não pode atravessar); aparência (cor, espessura, tipo de linha); rótulo (texto exato, se houver) e sua posição; e como evitar sobreposição com outros desenhos/setas. Regras obrigatórias: setas de identificação terminam exatamente na estrutura indicada, sem encostar em outra; linhas de identificação podem não ter ponta quando isso ajudar a clareza; setas de processo ligam explicitamente a origem ao destino correspondente; NUNCA uma seta contínua atravessando várias etapas de forma ambígua; NUNCA seta bidirecional para processo unidirecional — havendo fluxos opostos, use duas setas independentes; nenhuma ponta pode ficar flutuando entre dois destinos possíveis; nenhuma seta atravessa membrana, parede ou outro limite sem que essa passagem faça parte do processo representado; use aparências diferentes para seta de identificação e seta de fluxo quando houver risco de confusão; em ciclos, especifique também a conexão entre a última etapa e a primeira; em cadeias/teias alimentares, a seta de transferência de matéria/energia parte SEMPRE do organismo que serve de alimento e chega ao consumidor; em cladogramas, detalhe os pontos de ramificação e o parentesco representado, sem sugerir que um grupo atual é "mais evoluído" que outro. O sentido de CADA seta tem de corresponder exatamente ao que o texto-base, o comando, as alternativas ou a resolução afirmam sobre aquele fenômeno — havendo dúvida, releia a resolução antes de decidir, e repita a direção com outras palavras ao final da ficha da seta quando o sentido for o que a questão avalia.

5. TEXT LABELS — para CADA rótulo, escreva: o texto EXATO entre ASPAS SIMPLES, o elemento a que pertence, o lado em que fica, alinhamento, tamanho relativo, cor, se há linha de chamada, e uso de itálico/subscrito/sobrescrito quando aplicável (ex.: nomes científicos em itálico). Use aspas simples em TODA a especificação — ela viaja dentro de um campo JSON e aspas duplas não escapadas quebram a resposta. Regras: (a) TODO texto visível deve estar em PORTUGUÊS, com acentuação correta, ainda que a especificação esteja em inglês — inclua "all visible text must be rendered exactly as written above, in Portuguese, with correct accentuation"; (b) proibido inventar títulos, legendas, explicações ou marcas-d'água; (c) proibido nomear estruturas que o próprio enunciado pede para o aluno identificar — isso entregaria a resposta; (d) o rótulo fica FORA do contorno do elemento, nunca sobreposto, e nunca sobre região visualmente complexa; (e) nem rótulo sem elemento, nem elemento essencial sem rótulo; (f) não repita rótulos sem necessidade; (g) se dois rótulos correrem risco de se aproximar, declare os lados opostos; (h) declare tamanho legível ("labels in a clear sans-serif typeface, legible when printed at half page width"); (i) preserve a escrita correta de símbolos, fórmulas e unidades. Se a figura usar letras como "A", "B", "C" para identificar estruturas, defina a posição exata de cada uma e a estrutura indicada, e confirme que esses identificadores coincidem com os usados no enunciado e nas alternativas.

6. NUMBERS, SCALES AND MEASUREMENT MARKS — havendo dado referencial (régua, escala graduada, marcações de tempo/tamanho/concentração, valores em eixo, unidades), liste os valores EXATOS, onde cada um aparece e de que lado do traço fica impresso — sempre os mesmos valores do texto-base, do comando, das alternativas e da resolução, nunca aproximados. Quanto a proporções e ampliações: mantenha proporções biologicamente coerentes; diga quais estruturas podem ser ampliadas por razão didática; se painéis diferentes usam a mesma escala; se o desenho está deliberadamente fora de escala; e se a comparação de tamanhos é relevante para a resposta. NÃO invente barras de escala, medidas ou fatores de ampliação microscópica — use-os só quando os valores forem dados pelo enunciado ou puderem ser determinados de forma confiável a partir dele; em comparações, mantenha o tamanho de referência consistente, pois uma mudança de escala não pode simular uma diferença biológica inexistente. Havendo gráfico ou tabela embutidos na própria imagem, especifique: tipo de gráfico, variáveis dos eixos, unidades, intervalos e marcações, valores/pontos exatos a representar, quantidade de curvas/séries, cores/padrões/símbolos, legendas e tendências relevantes; para tabela, quantidade de linhas/colunas, cabeçalhos, conteúdo exato de cada célula, unidades e ordem dos dados — nunca delegue ao gerador a invenção de dados ou o posicionamento aproximado de valores.

7. STYLE AND LEGIBILITY — a imagem tem DUAS CAMADAS, e as duas são obrigatórias.

   ⛔ REGRA NÃO NEGOCIÁVEL DE REALISMO — vale para toda imagem cuja representação (definida na seção 1) não seja um diagrama relacional abstrato (cladograma, cadeia/teia alimentar, gráfico): ela tem de ser ULTRA-REALISTA ou, no mínimo, SEMI-ULTRA-REALISTA — nunca clipart, nunca desenho chapado tipo livro didático genérico. Mesmo um esquema (célula, corte de órgão, ciclo) deve ser tratado como uma ilustração/render 3D fotorrealista de conteúdo científico — nunca uma imagem plana e simples — SEM, no entanto, recorrer a efeitos cinematográficos, iluminação dramática, texturas ou hiper-realismo que possam distorcer a leitura das estruturas, das proporções ou das relações espaciais definidas nas seções 1 e 3. Peça, em inglês, termos como "photorealistic 3D scientific render, physically-based rendering, anatomically accurate proportions, clean even lighting that preserves structural clarity" — priorizando SEMPRE a legibilidade científica sobre o espetáculo visual.

   ▸ CAMADA 1 — BASE DE ILUSTRAÇÃO CIENTÍFICA REALISTA: renderização 3D fotorrealista, definição alta, foco nítido no assunto, iluminação uniforme que não esconda nenhuma estrutura, profundidade de campo suave apenas quando não comprometer a leitura de nenhum elemento. Peça, em inglês: "ultra-realistic 4K scientific illustration, three-dimensional photorealistic render, sharp focus throughout all labeled structures, even and clear lighting, rich but accurate material textures, museum-quality biology textbook illustration". Nunca chapada, genérica, borrada ou pixelizada — mas também nunca decorativa a ponto de comprometer a exatidão anatômica.

   ▸ CAMADA 2 — CAMADA DE ANOTAÇÃO (precisão): por cima da cena, camada vetorial limpa com as setas (seção 4), os rótulos (seção 5) e as marcações (seção 6), em princípios de UI/UX: hierarquia visual clara, tipografia sans-serif de tamanhos consistentes, mesma cor para o mesmo tipo de elemento, espaçamento generoso, contraste garantido contra o fundo. Peça, em inglês: "clean vector annotation overlay in modern UI/UX infographic style, consistent labeling system, clear visual hierarchy, high contrast between annotation and background, thin leader lines, subtle translucent backing plates wherever the scene behind the text is busy".

   ▸ REGRA DE PRECEDÊNCIA (não negociável): a Camada 1 NUNCA prejudica a Camada 2 nem a exatidão científica. Se a cena ameaçar a leitura de um rótulo, seta ou marcação, a cena cede. Declare no prompt, em inglês: "the realistic rendering must never obscure the annotation layer or distort anatomical accuracy; every label, arrow and structure must remain fully legible and scientifically correct".

   ▸ CORES, PADRÕES E CONVENÇÕES: defina uma paleta funcional — qual cor corresponde a cada estrutura/categoria, qual significado cada cor tem, quais elementos compartilham a mesma cor, quais precisam ser visualmente distintos, e quais padrões/contornos complementam a distinção por cores (a cor nunca é o único meio de transmitir uma informação indispensável). Ao usar cores convencionais (ex.: vermelho/azul em esquema circulatório), declare explicitamente o significado da convenção — NUNCA trate a cor convencional como aparência real do material biológico (não é correto sugerir, por exemplo, que todo vaso arterial carrega sangue mais oxigenado sempre, ou que o sangue venoso é realmente azul). Mantenha a mesma convenção de cores em todos os painéis da mesma figura.

   ▸ FIDELIDADE: o padrão de produção jamais custa exatidão científica. A cena reflete EXATAMENTE a situação-problema — mesma estrutura, mesmo processo, mesmo momento, mesmos valores. PROIBIDO acrescentar elementos espetaculares alheios à questão só para impressionar: tudo que a questão não previu vira ruído ou erro conceitual.

8. NEGATIVE CONSTRAINTS — encerre com duas listas. Primeiro, a lista genérica: "no decorative text, no watermark, no signature, no caption bar, no extra arrows, no additional objects beyond those listed above, no duplicated labels, no cropped or cut-off elements, no text in any language other than Portuguese, no flat clipart or generic cartoon style, no cinematic lighting effects that obscure structures, no blurry, pixelated or low-detail rendering, no annotation hidden or obscured by the scene". Segundo, UMA LISTA ESPECÍFICA PARA ESTA FIGURA, escrita por você a partir do conteúdo real da questão (nunca genérica): inclua, quando pertinentes, restrições como "no duplicated nuclei/organelles/chromosomes beyond the exact count specified", "no compartments connected without an anatomical communication between them", "no reversed flow direction on any arrow", "no structure placed outside its correct anatomical compartment", "no confusing homologous structures with analogous ones", "no missing steps required to interpret the cycle", "no extra organisms or feeding relationships beyond those listed", "no chromosome/chromatid/molecule count inconsistent with the situation described", "no label that reveals the structure the student is asked to identify", "no detail contradicting the textoBase, comando or resolução".

VERIFICAÇÃO ANTES DE ENTREGAR — BIOLOGIA: releia a "descricao", o texto-base, o comando, as alternativas e a resolução e confirme que (i) todo elemento citado como visível consta do ELEMENT INVENTORY, com a quantidade exata; (ii) toda seta tem ficha completa (origem, destino, ponta, trajeto, sentido) na seção ARROWS, e o sentido de cada uma corresponde exatamente ao fenômeno descrito; (iii) todo rótulo tem texto exato, elemento dono e lado, e nenhum rótulo entrega a resposta que o aluno deveria deduzir; (iv) todo número/proporção citado na questão aparece com o MESMO valor na seção NUMBERS, e nenhuma escala foi inventada; (v) a orientação anatômica (vista, plano de corte, dentro/fora, adjacências) está inequívoca; (vi) as cores seguem uma convenção consistente e claramente definida, nunca sugerindo uma aparência real inexistente; (vii) em sequências/ciclos, as etapas estão na ordem correta e a conexão entre a última e a primeira (quando for ciclo) está explícita; (viii) nenhuma simplificação didática altera o significado científico do fenômeno; (ix) a "lista específica desta figura" da seção NEGATIVE CONSTRAINTS reflete riscos concretos do conteúdo, não uma lista genérica; (x) nada foi afirmado na "descricao" que não esteja especificado no "promptImagem", e nenhum dado essencial da imagem ficou de fora da "descricao". Nunca declare a especificação pronta se qualquer um destes pontos falhar — reescreva a seção correspondente antes de entregar.`,
  grafico: `Recurso visual: GRÁFICO. A questão deve depender de um gráfico com dados numéricos plausíveis e coerentes (cientificamente ou matematicamente consistentes com o texto-suporte), efetivamente necessários para resolver a questão — não apenas decorativos. Preencha "recurso":"grafico" e "visual" com: {"tipo":"grafico","chartType":"bar" ou "line" ou "pie","titulo":"...","labels":["...","..."],"datasets":[{"label":"...","data":[num,num,...]}]}. Os números usados no gráfico devem ser os mesmos que a resolução comentada utiliza.`,
  tabela: `Recurso visual: TABELA. A questão deve depender de uma tabela com dados relevantes (resultados experimentais, dados populacionais, séries históricas, comparações entre grupos etc.), efetivamente necessários para resolver a questão. Preencha "recurso":"tabela" e "visual" com: {"tipo":"tabela","titulo":"...","colunas":["...","..."],"linhas":[["...","..."],["...","..."]]}.`,
};

// Seleciona as instruções de recurso visual a usar. Para Biologia + imagem, usa
// um protocolo dedicado (RECURSO_INSTRUCOES.imagem_biologia) que incorpora as
// exigências científicas específicas da disciplina (inventário detalhado de
// estruturas, ficha por seta, orientação anatômica, convenção de cores, listas
// de restrições específicas da figura etc.) mantendo as mesmas 8 seções e a
// mesma exigência de realismo fotográfico/3D já usadas para as demais
// disciplinas — nunca duas fontes de verdade divergentes para o mesmo campo.
export function instrucoesImagem(recurso: string, disciplina: string): string {
  if (recurso === "imagem" && (disciplina || "").trim().toLowerCase() === "biologia") {
    return RECURSO_INSTRUCOES["imagem_biologia"];
  }
  return RECURSO_INSTRUCOES[recurso];
}

export const JSON_SCHEMA_TXT = `Responda SOMENTE com um objeto JSON válido (sem markdown, sem texto antes ou depois, sem comentários), exatamente neste formato:
{
 "area": "string",
 "disciplina": "string",
 "tema": "string",
 "dificuldade": "Fácil" | "Médio" | "Difícil",
 "competencia": {"numero": number, "texto": "string (texto oficial completo da competência)"},
 "habilidade": {"codigo": "HXX", "texto": "string (texto oficial completo da habilidade)"},
 "objetoConhecimento": "string (título do objeto de conhecimento oficial da área, copiado literalmente da lista de OBJETOS DE CONHECIMENTO OFICIAIS apresentada no prompt do sistema — nunca um objeto inventado)",
 "recurso": "nenhum" | "imagem" | "grafico" | "tabela",
 "visual": null ou objeto conforme instruído acima,
 "textoBase": "string (texto-suporte com contextualização; termine com a citação de fonte no formato ENEM — real ou verossímil, EXCETO quando a regra 'PROIBIDO INVENTAR AUTORES OU TEXTOS' abaixo se aplicar à disciplina, caso em que a fonte citada TEM que ser real. Separe o corpo do texto da citação final com uma quebra de parágrafo DE VERDADE — nunca escreva os dois caracteres literais \\n no meio do texto para representar essa quebra; se precisar de uma quebra de linha dentro da própria string JSON, produza-a como quebra de linha real, não como texto \\n)",
 "comando": "string (o enunciado da pergunta, curto, indireto, SEM nenhum ponto de interrogação — é sempre uma frase afirmativa que se completa com as alternativas, nunca uma pergunta direta)",
 "alternativas": {"A":"string","B":"string","C":"string","D":"string","E":"string"},
 "gabarito": "A" | "B" | "C" | "D" | "E",
 "resolucaoComentada": "string (explicação detalhada do raciocínio para chegar à resposta correta)",
 "analiseAlternativas": {
   "A": {"status":"correta"|"incorreta","comentario":"string"},
   "B": {"status":"correta"|"incorreta","comentario":"string"},
   "C": {"status":"correta"|"incorreta","comentario":"string"},
   "D": {"status":"correta"|"incorreta","comentario":"string"},
   "E": {"status":"correta"|"incorreta","comentario":"string"}
 }
}
No campo "comentario" de cada alternativa errada, nomeie explicitamente o tipo de distrator (leitura parcial, inversão de causa/efeito, verdade parcial, anacronismo/confusão conceitual, senso comum, erro de processo, excesso de escopo, reaproveitamento fora de contexto) e explique EM TERMOS CONCEITUAIS o raciocínio equivocado que ela representa — nunca justifique a incorreção apenas apontando que a alternativa usa uma palavra absoluta/extrema; a palavra não é o motivo do erro, o raciocínio é. Nunca deixe mais de uma alternativa com status "correta".

REGRA DE FORMATAÇÃO DO JSON — vale para TODOS os campos de texto, e o campo "promptImagem" é o mais sensível porque cita o texto dos rótulos:
- prefira ASPAS SIMPLES dentro dos textos; se precisar mesmo de uma aspa dupla, escape-a como \\" ;
- nada de LaTeX nem de barra invertida solta: escreva "2π vezes a raiz quadrada de (L/g)", nunca "2\\\\pi\\\\sqrt{L/g}";
- nada de quebra de linha literal dentro de uma string (use \\n);
- nada de vírgula sobrando antes de } ou ].

COMO ENTREGAR: chame a ferramenta "entregar_questao" passando esse objeto como argumento. Não escreva o JSON no texto da resposta, não use crases e não escreva nada antes ou depois da chamada da ferramenta.`;

